version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "8002:8002"
  backend:
    build: ./backend_app_taker/
    ports:
      - "6200:6200"
    volumes:
      - ./backend_app_taker:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend_app_taker/
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_app_taker:/usr/src/app
    depends_on:
      - backend
  auth:
    build: ./auth_app_taker/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./auth_app_taker:/usr/src/app
    depends_on:
      - frontend
